"""add photo_path and default_opening_amount

Revision: 7c8b9ba73ebf
Anterior: de0341f4debd
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7c8b9ba73ebf'
down_revision: Union[str, None] = 'de0341f4debd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    with op.batch_alter_table('business_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_opening_amount', sa.Numeric(precision=12, scale=2), nullable=False, server_default='0'))

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('photo_path')

    with op.batch_alter_table('business_settings', schema=None) as batch_op:
        batch_op.drop_column('default_opening_amount')
    # ### end Alembic commands ###
